### ISSUE TITLE
Bold Text tag- \textbf{ } not working

### ISSUE THREAD

**Issue by HabibRh26** [anthonyattard/Deedy-Resume-Cover-Letter#2]
`\textbf{ }` is not working applied to any text inside the `\letter content` tag. How to use that?

**Comment by anthonyattard** [comment]
@HabibRh26 Styling is not allowed in `.xtx` files within tags, only of freeform text. 

In order to have a different style font you will need to make a new element in the `.cls` file that has the bold styling.

A quick example:
.cls file
```latex
% Letter content command
\newcommand{\lettercontent}[1]{\raggedright\fontspec{Calibri}\fontsize{12pt}{14pt}\selectfont {#1 \\}\mbox{}\\ \normalfont}
\newcommand{\lettercontentbold}[1]{\raggedright\fontspec{Calibri Bold}\fontsize{12pt}{14pt}\selectfont {#1 \\}\mbox{}\\ \normalfont}
```

.xtx file
```latex
\lettercontent{Regular text,}
\lettercontentbold{Bold text}
```

Another option is to not use the `\letter content` tag but just have it be outside of brackets, in that case the font will take the default styling and would be compatible with ` \textbf{ }`

Hope that helps.
